name = "GPP_SUGRA"
uuid = "8d9ff2b0-75c1-4dff-966b-4cbe4ff0675a"
authors = ["not-physicist"]
version = "0.1.0-DEV"

[deps]
LinearInterpolations = "b20c7882-2490-4592-a606-fbbfe9e745e8"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
NPZ = "0.4"
OrdinaryDiffEq = "6"
StaticArrays = "1"
julia = ">=1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
