name = "GPP_SUGRA"
uuid = "8d9ff2b0-75c1-4dff-966b-4cbe4ff0675a"
authors = ["not-physicist"]
version = "0.1.0-DEV"

[deps]
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
NPZ = "0.4"
NumericalIntegration = "0.3"
Interpolations = "0.15"
StaticArrays = "1"
Folds = "0.2"
julia = ">=1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
